# Generated by Django 4.2.1 on 2023-05-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessModelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_model_type', models.CharField(max_length=255)),
                ('business_model_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IndustryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_type', models.CharField(max_length=255)),
                ('industry_description', models.CharField(max_length=255)),
            ],
        ),
    ]
