# Generated by Django 4.2.1 on 2023-05-12 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busines_name', models.CharField(max_length=255)),
                ('business_idea', models.TextField()),
                ('pricing_model', models.TextField()),
                ('finance_model', models.TextField()),
                ('marketing_strategy', models.TextField()),
                ('white_paper', models.TextField()),
                ('date_generated', models.DateTimeField(auto_now_add=True)),
                ('logo', models.ImageField(upload_to='business_ideas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
