# Generated by Django 4.2.1 on 2023-05-12 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea_jet_business', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessidea',
            old_name='busines_name',
            new_name='business_name',
        ),
    ]
