# Generated by Django 4.2.1 on 2023-05-24 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idea_jet_business', '0002_rename_busines_name_businessidea_business_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessidea',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_ideas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('business_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='idea_jet_business.businessidea')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_step', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('business_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_steps', to='idea_jet_business.businessidea')),
            ],
        ),
    ]
