# Generated by Django 4.2.1 on 2023-05-24 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea_jet_catalog', '0001_initial'),
        ('idea_jet_business', '0003_alter_businessidea_user_feature_executionstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessidea',
            name='business_model',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='idea_jet_catalog.businessmodeltype'),
        ),
        migrations.AddField(
            model_name='businessidea',
            name='industy_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='idea_jet_catalog.industrytype'),
        ),
    ]
