# Generated by Django 4.2.1 on 2023-05-24 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea_jet_business', '0004_businessidea_business_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessidea',
            name='finance_model',
        ),
        migrations.RemoveField(
            model_name='businessidea',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='businessidea',
            name='marketing_strategy',
        ),
        migrations.RemoveField(
            model_name='businessidea',
            name='pricing_model',
        ),
        migrations.RemoveField(
            model_name='businessidea',
            name='white_paper',
        ),
    ]
