# Generated by Django 4.2.1 on 2023-05-24 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idea_jet_business', '0006_rename_industy_type_businessidea_industry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessidea',
            name='original_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='original_business_ideas', to=settings.AUTH_USER_MODEL),
        ),
    ]
