# Generated by Django 4.2.1 on 2023-05-25 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea_jet_business', '0007_businessidea_original_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField()),
                ('type', models.CharField(choices=[('INITIAL', 'INITIAL')])),
                ('business_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idea_jet_business.businessidea')),
            ],
        ),
    ]
