# Generated by Django 4.2.1 on 2023-05-25 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea_jet_business', '0008_conversationsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('target_market', models.TextField()),
                ('market_size', models.TextField()),
                ('pricing_model', models.TextField()),
                ('barriers', models.TextField()),
                ('market_positioning', models.TextField()),
                ('business_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idea_jet_business.businessidea')),
            ],
        ),
    ]
