# Generated by Django 4.2.1 on 2023-05-25 21:16

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea_jet_business', '0009_marketresearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('key_features', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('competitive_advantage', models.TextField()),
                ('business_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='idea_jet_business.businessidea')),
            ],
        ),
    ]
