# Generated by Django 4.2.1 on 2023-06-03 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea_jet_business', '0012_businessgeneration_businessidea_business_generation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessidea',
            name='business_generation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='business_ideas', to='idea_jet_business.businessgeneration'),
        ),
    ]
