# Generated by Django 4.2.1 on 2023-06-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea_jet_business', '0013_alter_businessidea_business_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessgeneration',
            name='status',
            field=models.CharField(default='PENDING'),
        ),
    ]
