# Generated by Django 4.2.1 on 2023-06-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea_jet_business', '0014_businessgeneration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessidea',
            name='product',
            field=models.TextField(default=''),
        ),
    ]
