industry_list = [
"Technology (Software and Hardware)",
"Finance and Banking",
"Healthcare and Pharmaceuticals",
"Energy (Oil, Gas, and Renewable Energy)",
"Retail and E-commerce",
"Manufacturing (Automobiles, Aerospace, and Defense)",
"Telecommunications",
"Consumer Goods",
"Real Estate and Property Development",
"Entertainment and Media",
"Transportation and Logistics",
"Hospitality and Tourism",
"Agriculture and Food Production",
"Construction and Engineering",
"Chemicals",
"Professional Services (Legal, Consulting, Accounting)",
"Biotechnology and Life Sciences",
"Education and Training",
"Insurance",
"Fashion and Apparel",
"Mining and Metals",
"Pharmaceuticals",
"Advertising and Marketing",
"Aerospace and Defense",
"Automotive",
"Beverages (Alcoholic and Non-alcoholic)",
"Broadcasting (TV and Radio)",
"Computer Services",
"Electronics",
"Environmental Services",
"Gaming and Casinos",
"Home Furnishings",
"Internet Services and Social Media",
"Medical Devices and Equipment",
"Music and Recording",
"Office Supplies and Equipment",
"Online Streaming",
"Publishing and Printing",
"Sports and Recreation",
"Tobacco",
"Utilities (Water, Gas, and Electric)",
"Wholesale Trade",
"Airline Industry",
"Pharmaceuticals Retail",
"Pharmaceuticals Wholesale",
"Software Development",
"Renewable Energy Equipment Manufacturing",
"Data Processing and Hosting Services",
"Social Networking",
"Video Game Development"
]