## when generating a random business use this list to put in a random group of entrepreneurs
entrepreneuers = [
    "Jeff Bezos", 
    "Bill Gates", 
    "Elon Musk", 
    "Mark Zuckerberg", 
    "Warren Buffett", 
    "Larry Ellison", 
    "Larry Page", 
    "Sergey Brin", 
    "Michael Bloomberg", 
    "Jack Ma", 
    "Carlos Slim Helú", 
    "Amancio Ortega", 
    "Steve Ballmer", 
    "Mukesh Ambani", 
    "Francoise Bettencourt Meyers", 
    "Bernard Arnault", 
    "Jim Walton", 
    "Alice Walton", 
    "Rob Walton", 
    "Ma Huateng", 
    "Larry Robbins", 
    "Elon Musk", 
    "Kirsten Rausing", 
    "Jacqueline Mars", 
    "John Mars", 
    "Leonardo Del Vecchio", 
    "Len Blavatnik", 
    "Dieter Schwarz", 
    "Michael Dell", 
    "Phil Knight", 
    "Gautam Adani", 
    "Azim Premji", 
    "Stefan Persson", 
    "Tadashi Yanai", 
    "Lee Shau Kee", 
    "Charlene de Carvalho-Heineken", 
    "David Thomson", 
    "Jacqueline Mars", 
    "John Mars", 
    "Savitri Jindal", 
    "Jim Simons", 
    "Susanne Klatten", 
    "Vladimir Lisin", 
    "Lui Che Woo", 
    "Giovanni Ferrero", 
    "Leonard Lauder", 
    "Laurene Powell Jobs", 
    "Rupert Murdoch", 
    "Lakshmi Mittal"
]
